title: "amerigo novaro"
url: "https://amerigonovaro.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://amerigonovaro.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "/publications"
 - name: "Talks"
   link: "/talks"
